### PR TITLE
Updates for changes in rusoto/rusoto#21.

### PR DESCRIPTION
**Pull request by jimmycuadra**
This is an almost-working version of this crate updated for all the changes in rusoto/rusoto#201. I did my best to make sense of what was being done before, but someone more familiar with these helpers will need to take it the rest of the way.

### CODE REVIEW

**Comment by matthewkmayer** [comment]
Testing the SQS functionality shows we've modified the return types a lot, where we return things nested much more.  `$ ~/Documents/rusoto_helpers$ cargo test --features sqs`

Before:

```rust
for msg in response.messages {
     println!("Received message '{:?}' with id {}", msg.body, msg.message_id);
     try!(sqs.delete_message(&queue_url.unwrap(), &msg.receipt_handle));
}
```

Hacky after that still doesn't compile for reasons listed later:

```rust
// receive a message
    let response = try!(sqs.receive_message(&queue_url.unwrap()));
    match response.messages {
        Some(messages) => {
            for msg in messages {
                println!("Received message '{:?}' with id {}", msg.body, msg.message_id.unwrap());
                try!(sqs.delete_message(&queue_url.unwrap(), &msg.receipt_handle.unwrap()));
            }
        },
        None => println!("no messages")
    }
```

Hacky version compiles but the borrow checker throws its weight around:

```bash
tests/sqs.rs:48:43: 48:52 error: cannot move out of borrowed content [E0507]
tests/sqs.rs:48     let response = try!(sqs.send_message(&queue_url.unwrap(), msg_str));
```

(and more borrow checker being grumpy)

I'll keep prodding this, but these are areas currently stopping us.

**Comment by matthewkmayer** [comment]
I did some more work on this after merging https://github.com/rusoto/rusoto/pull/206 .  I'm not sure if the changes I made around clients now taking a generic AWS credential provider is right or not and the `create_queue` call isn't working:

`~/Documents/rusoto_helpers$ cargo test --features sqs -- --nocapture`

 `Got error: HTTP response code for CreateQueue: 400`.

Still working on things.

**Comment by matthewkmayer** [comment]
Ah, looks like there's a problem with the codegen in Rusoto:

`DEBUG:hyper::http::h1: request line: Post "/?Action=CreateQueue&String=test_q_1459743894" Http11`

It should be `QueueName=test_q...` per http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html .

**Comment by matthewkmayer** [comment]
https://github.com/rusoto/rusoto/pull/209 should do it, then we can get back on this PR.

**Comment by matthewkmayer** [comment]
Still got some juggling to do around SQS tests that are commented out.

**Comment by matthewkmayer** [comment]
Phoey, tests were incorrectly reporting as passing - seeing an error on ListQueues now.  I think it got into a state where queues were created, then subsequent test runs caused something to be present in the ListQueues response which causes an error.  Off to make an issue in the Rusoto repo.

**Comment by matthewkmayer** [comment]
SQS and Dynamodb features work for integration tests, KMS has some refactoring to do from the Rusoto codegen change, I'll pound on that right now.

**Comment by matthewkmayer** [comment]
I think this is ready to go, a review of my code changes would be great.

KMS integrations tests will come over with PR #6 .

**Comment by jimmycuadra** [comment]
LGTM

**Pull request merged**
